version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.22

jobs:
  # STAGING FRONTEND
  deploy-staging-web:
    working_directory: ~/giribil-web
    docker:
      - image: circleci/node:10.13.0 
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            echo "export GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> web/.env
            echo "export API_URL=$API_URL" >> web/.env
            echo "export GIRBIL_WEB_STAGING_S3_CLIENT=$GIRBIL_WEB_STAGING_S3_CLIENT" >> $BASH_ENV
            echo "export GIRBIL_WEB_STAGING_CLOUNDFRONT_ID=$GIRBIL_WEB_STAGING_CLOUNDFRONT_ID" >> $BASH_ENV
      - restore_cache:
          key: dependency-cache-{{ checksum "web/package.json" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "shared/package.json" }}
      - run:
          name: Install Web Packages
          command: cd web/ && yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "web/package.json" }}
          paths:
            - ./web/node_modules
      - run:
          name: Install Shared Packages
          command: cd shared/ && yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "shared/package.json" }}
          paths:
            - ./shared/node_modules
      - run:
          name: deploy client app
          command: |
            sudo apt-get install awscli
            aws configure set preview.cloudfront true
            sh scripts/deploy-web.sh

  deploy-staging-api:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          command: |
            cd api && sudo scripts/deploy.sh

workflows:
  deploy_staging_web:
    jobs:
      - deploy-staging-web:
          filters:
            branches:
              only: staging

  deploy_staging_api:
    jobs:
      - deploy-staging-api:
          filters:
            branches:
              only: master