version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/girbil
hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ubuntu
