version: '3'

services:
  gilbil-server:
    container_name: girbil-api
    image: node:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes: 
      - .:/var/www
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - girbil_network
    command: >
      bash -c "yarn migrate && yarn dev" 

  postgres:
    container_name: girbil-db
    image: postgres:12.1-alpine
    environment:
      POSTGRES_PASSWORD: girbil
      POSTGRES_USER: root
      POSTGRES_DB: girbil
    ports:
      - "5433:5432"
    networks:
      - girbil_network
  redis:
    container_name: girbil-redis
    image: redis:6.0-rc1-alpine
    ports:
      - "6379:6379"
    networks:
      - girbil_network
networks:
  girbil_network:
    driver: bridge